[package]
name = "mithril"
version = "0.10.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "mithril"

[dependencies]
groestl = "0.9.0"
blake = "2.0.1"
jh-ffi = "0.5.0"
skein-ffi = "0.5.0"
serde = "1.0.116"
serde_json = "1.0.57"
serde_derive = "1.0.116"
config = "0.10.1"
log = "0.4.11"
env_logger = "0.7.1"
num_cpus = "1.13.0"
bandit = "0.12.2"
byteorder = "1.3.4"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dirs = "3.0.1"
crossbeam-channel = "0.4.4"
